export type UserRole = 'agent' | 'supervisor' | 'admin';

type UserProfile = {
  role: UserRole;
  department: string;
  representative?: string;
  trademarkAccess?: string[];
  hiddenBrands?: string[];
};

export const userAccessMap: Record<string, UserProfile> = {
  'oliahrynyk32@gmail.com': {
    role: 'agent',
    department: 'Область (Центр)',
    representative: 'Гриник Ольга',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'storoshdiana@gmail.com': {
    role: 'agent',
    department: 'Місто',
    representative: 'Довга Діана',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'dyug.tany.90@gmail.com': {
    role: 'agent',
    department: "Кам'янець-Подільський відділ",
    representative: 'Дюг Тетяна',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'ivsn.denis@gmail.com': {
    role: 'agent',
    department: "Кам'янець-Подільський відділ",
    representative: 'Івасишин Денис',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'anna.stetsyuk25@gmail.com': {
    role: 'agent',
    department: 'Шепетівський відділ',
    representative: 'Кучер Аня',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'laptevahm@gmail.com': {
    role: 'agent',
    department: 'Місто',
    representative: 'Лаптєва Руслана',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'olenkapolonne@gmail.com': {
    role: 'agent',
    department: 'Шепетівський відділ',
    representative: 'Мартинчик Альона',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'glukhovska.84@gmail.com': {
    role: 'agent',
    department: 'Область (Центр)',
    representative: 'Могильна Оксана',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'svetlananagornak1984@gmail.com': {
    role: 'agent',
    department: 'Шепетівський відділ',
    representative: 'Нагорняк Світлана',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'vlad-oliynik@ukr.net': {
    role: 'agent',
    department: "Кам'янець-Подільський відділ",
    representative: 'Олійник Влад',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'alinakukolka84@gmail.com': {
    role: 'agent',
    department: 'Область (Центр)',
    representative: 'Сторожук Аліна',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'irashwetc89@gmail.com': {
    role: 'agent',
    department: 'Шепетівський відділ',
    representative: 'Швець Ірина',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'natasha14148282@icloud.com': {
    role: 'agent',
    department: 'Місто',
    representative: 'Ящишина Наталія',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'y.stepanishin@gmail.com': {
    role: 'admin',
    department: 'Усі відділи',
    representative: 'Юрій Степанишин',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'gutovskan@gmail.com': {
    role: 'admin',
    department: 'Усі відділи',
    representative: 'Гутовська Наталія',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'vkamsnskiy@gmail.com': {
    role: 'supervisor',
    department: "Кам'янець-Подільський відділ",
    representative: 'Камінський Володимир',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'nikolya202@gmail.com': {
    role: 'supervisor',
    department: 'Шепетівський відділ',
    representative: 'Микола Швець',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'w18051985@gmail.com': {
    role: 'supervisor',
    department: 'Місто, Область (Центр)',
    representative: 'Токарчук Микола',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA',
      'Деліція',
    ],
  },
  'valentyna.korniienko@tctrade.com.ua': {
    role: 'admin',
    department: 'Усі відділи',
    representative: 'Корнієнко Валентина',
    trademarkAccess: [
      'Greenfield',
      'TESS',
      'Принцеса Нурі',
      'Принцеса Ява',
      'Принцеса Гіта',
      'Принцеса Канді',
      'Жокей',
      'JARDIN',
      'PIAZZA'  
    ],
  },
};

export const allowedEmails = Object.keys(userAccessMap);
